#define SUNDAY  "Dimanche"  // "Dimanche"
#define MONDAY  "Lundi"  // "Lundi"
#define TUESDAY  "Mardi"  // "Mardi"
#define WEDNESDAY  "Mercredi"  // "Mercredi"
#define THURSDAY  "Jeudi"  // "Jeudi"
#define FRIDAY  "Vendredi"  // "Vendredi"
#define SATURDAY  "Samedi"  // "Samedi"
  
#define JANUARY  "janvier"  // "janvier"
#define FEBRUARY  "f\x2avrier"  // "février"
#define MARCH  "mars"  // "mars"
#define APRIL  "avril"  // "avril"
#define MAY  "mai"  // "mai"
#define JUNE  "juin"  // "juin"
#define JULY  "juillet"  // "juillet"
#define AUGUST  "ao\x2at"  // "août"
#define SEPTEMBER  "septembre"  // "septembre"
#define OCTOBER  "octobre"  // "octobre"
#define NOVEMBER  "novembre"  // "novembre"
#define DECEMBER  "d\x2acembre"  // "décembre"
  
#define DOMOTICZ_OFF_LINE "Domo en panne"  // "Domo en panne"
