/*
 * 
 * fr printable characters + degree and Euro symbols + 0x32 to 0x7e ASCII
 * **********************************************************************
 * 
 * À Â Ä É È Ê Ë Î Ï Ô Ö Ù Û Ü Ÿ Ç Æ Œ « °
 * à â ä é è ê ë î ï ô ö ù û ü ÿ ç æ œ » €
 * 			
 */
 
#define CHARSET_NAME "FR"

#define MAKE_CHARSET

#define INCLUDE_ASCII

struct chardef chartable[] = {
    {  0x00ab, "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK"},
    {  0x00b0, "DEGREE SIGN"},
    {  0x00bb, "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK"},
    {  0x00c0, "LATIN CAPITAL LETTER A WITH GRAVE"},
    {  0x00c2, "LATIN CAPITAL LETTER A WITH CIRCUMFLEX"},
    {  0x00c4, "LATIN CAPITAL LETTER A WITH DIAERESIS"},
    {  0x00c6, "LATIN CAPITAL LETTER AE"},
    {  0x00c7, "LATIN CAPITAL LETTER C WITH CEDILLA"},
    {  0x00c8, "LATIN CAPITAL LETTER E WITH GRAVE"},
    {  0x00c9, "LATIN CAPITAL LETTER E WITH ACUTE"},
    {  0x00ca, "LATIN CAPITAL LETTER E WITH CIRCUMFLEX"},
    {  0x00cb, "LATIN CAPITAL LETTER E WITH DIAERESIS"},
    {  0x00ce, "LATIN CAPITAL LETTER I WITH CIRCUMFLEX"},
    {  0x00cf, "LATIN CAPITAL LETTER I WITH DIAERESIS"},
    {  0x00d4, "LATIN CAPITAL LETTER O WITH CIRCUMFLEX"},
    {  0x00d6, "LATIN CAPITAL LETTER O WITH DIAERESIS"},
    {  0x00d9, "LATIN CAPITAL LETTER U WITH GRAVE"},    
    {  0x00db, "LATIN CAPITAL LETTER U WITH CIRCUMFLEX"},
    {  0x00dc, "LATIN CAPITAL LETTER U WITH DIAERESIS"},
    {  0x00e0, "LATIN SMALL LETTER A WITH GRAVE"},
    {  0x00e2, "LATIN SMALL LETTER A WITH CIRCUMFLEX"},
    {  0x00e4, "LATIN SMALL LETTER A WITH DIAERESIS"},
    {  0x00e6, "LATIN SMALL LETTER AE"},
    {  0x00e7, "LATIN SMALL LETTER C WITH CEDILLA"},
    {  0x00e8, "LATIN SMALL LETTER E WITH GRAVE"},
    {  0x00e9, "LATIN SMALL LETTER E WITH ACUTE"},
    {  0x00ea, "LATIN SMALL LETTER E WITH CIRCUMFLEX"},    
    {  0x00eb, "LATIN SMALL LETTER E WITH DIAERESIS"},
    {  0x00ee, "LATIN SMALL LETTER I WITH CIRCUMFLEX"},
    {  0x00ef, "LATIN SMALL LETTER I WITH DIAERESIS"},
    {  0x00f4, "LATIN SMALL LETTER O WITH CIRCUMFLEX"},
    {  0x00f6, "LATIN SMALL LETTER O WITH DIAERESIS"},    
    {  0x00f9, "LATIN SMALL LETTER U WITH GRAVE"},
    {  0x00fb, "LATIN SMALL LETTER U WITH CIRCUMFLEX"},
    {  0x00fc, "LATIN SMALL LETTER U WITH DIAERESIS"},
    {  0x00ff, "LATIN SMALL LETTER Y WITH DIAERESIS"},
    {  0x0152, "LATIN CAPITAL LIGATURE OE"},    
    {  0x0153, "LATIN SMALL LIGATURE OE"},
    {  0x0178, "LATIN CAPITAL LETTER Y WITH DIAERESIS"},
    {  0x20ac, "EURO SIGN"}
};


